db.driver=org.sqlite.JDBC
db.url=jdbc:sqlite:../microblog/app.db
db.user=
db.password=
db.schema=
db.seed=
db.assert.dataset=examples/microblog-ui-expected.yml
db.assert.compare=EQUALS
db.assert.ignoreColumns=id,password_hash,last_seen,token,token_expiration,last_message_read_time,timestamp,user_id,language
db.cleanup.sql.ids=
db.seed.sql.ids=
